### ISSUE TITLE
ENOENT: no such file or directory, open 'testcert/key.pem'

### ISSUE THREAD

**Issue by Iazzetta** [mkg20001/voice-chat#3]
Error when I start project:

```
Guilherme:voice-chat guilhermex$ node index.js 
LOG	28.11.2017  11:21:40	main	Guilherme.localInit	
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'testcert/key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/Users/xxxxxxxx/workspace/voice-chat/core/express/index.js:3:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by EnzoPB** [comment]
Change your cert and private key path in core/express/index.js

**Comment by LuisEnMarroquin** [comment]
You have to create that cert
